parser: "babel-eslint"

parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true
    jsx: true
    experimentalObjectRestSpread: true

extends:
  - "airbnb"
  - "plugin:flowtype/recommended"

plugins:
  - "eslint-comments"
  - "flowtype"

settings:
  import/resolver:
    webpack:
      config: 'conf/webpack.config.babel.js'
  flowtype:
    onlyFilesWithFlowAnnotation: true

env:
  es6: true
  node: true
  browser: true

rules:
  no-plusplus: 0
  no-console: 0
  max-len: [2, 120]
  no-shadow: 0
  func-names: 0
  linebreak-style: [0]

  jsx-a11y/href-no-hash: 1
  jsx-a11y/label-has-for: 1
  jsx-a11y/img-redundant-alt: 0
  jsx-a11y/no-static-element-interactions: 0

  import/no-named-as-default: 0

  react/prop-types: 0
  react/jsx-filename-extension: 0
  react/require-default-props: 0
  react/prefer-stateless-function: 2
  react/no-unused-prop-types: 1

  eslint-comments/disable-enable-pair: "error"
  eslint-comments/no-duplicate-disable: "error"
  eslint-comments/no-unlimited-disable: "error"
  eslint-comments/no-unused-disable: "warn"
  eslint-comments/no-unused-enable: "warn"

globals:
  Microsoft: false